//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manitas.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class calificaciones_manitas
    {
        public System.Guid id { get; set; }
        public System.Guid servicio_id { get; set; }
        public System.Guid cliente_id { get; set; }
        public System.Guid manitas_id { get; set; }
        public short puntualidad { get; set; }
        public short calidad { get; set; }
        public short limpieza { get; set; }
        public short trato { get; set; }
        public short precio_justo { get; set; }
        public bool es_negativa { get; set; }
        public string comentario { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual usuario usuario { get; set; }
        public virtual usuario usuario1 { get; set; }
        public virtual servicio servicio { get; set; }
    }
}
