//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manitas.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cargos_comision
    {
        public System.Guid id { get; set; }
        public System.Guid ciclo_id { get; set; }
        public System.Guid servicio_id { get; set; }
        public decimal mano_obra_base { get; set; }
        public decimal porcentaje_aplicado { get; set; }
        public decimal monto_comision { get; set; }
        public System.DateTime fecha_cargo { get; set; }
    
        public virtual ciclos_comision ciclos_comision { get; set; }
        public virtual servicio servicio { get; set; }
    }
}
