//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manitas.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ciclos_comision
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ciclos_comision()
        {
            this.cargos_comision = new HashSet<cargos_comision>();
            this.pagos_comision = new HashSet<pagos_comision>();
        }
    
        public System.Guid id { get; set; }
        public System.Guid manitas_id { get; set; }
        public System.DateTime fecha_inicio { get; set; }
        public System.DateTime fecha_corte { get; set; }
        public System.DateTime fecha_limite_pago { get; set; }
        public string estado { get; set; }
        public decimal total_acumulado { get; set; }
        public bool notificacion_corte_enviada { get; set; }
        public bool notificacion_aviso_enviada { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cargos_comision> cargos_comision { get; set; }
        public virtual usuario usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pagos_comision> pagos_comision { get; set; }
    }
}
