//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manitas.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class colonia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public colonia()
        {
            this.direcciones_cliente = new HashSet<direcciones_cliente>();
        }
    
        public System.Guid id { get; set; }
        public string codigo_postal { get; set; }
        public string nombre { get; set; }
        public string tipo { get; set; }
        public string municipio { get; set; }
        public string estado { get; set; }
        public string ciudad { get; set; }
        public string zona_postal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<direcciones_cliente> direcciones_cliente { get; set; }
    }
}
