//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manitas.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class configuracion_sistema
    {
        public System.Guid id { get; set; }
        public string clave { get; set; }
        public string valor { get; set; }
        public string descripcion { get; set; }
        public bool editable { get; set; }
        public Nullable<System.Guid> modificado_por_id { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
    
        public virtual usuario usuario { get; set; }
    }
}
