//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manitas.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cotizacione
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cotizacione()
        {
            this.partidas_cotizacion = new HashSet<partidas_cotizacion>();
        }
    
        public System.Guid id { get; set; }
        public System.Guid servicio_id { get; set; }
        public string tipo { get; set; }
        public short numero_ronda { get; set; }
        public decimal total_mano_obra { get; set; }
        public decimal total_materiales { get; set; }
        public Nullable<short> sesiones_estimadas { get; set; }
        public string tiempo_estimado_texto { get; set; }
        public string estado { get; set; }
        public System.DateTime fecha_envio { get; set; }
        public Nullable<System.DateTime> fecha_respuesta { get; set; }
    
        public virtual servicio servicio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<partidas_cotizacion> partidas_cotizacion { get; set; }
    }
}
