//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manitas.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class diagnostico
    {
        public System.Guid id { get; set; }
        public System.Guid servicio_id { get; set; }
        public System.DateTime fecha_propuesta { get; set; }
        public System.TimeSpan hora_propuesta { get; set; }
        public string estado { get; set; }
        public Nullable<System.DateTime> fecha_confirmacion { get; set; }
        public bool recordatorio_24h_enviado { get; set; }
        public bool recordatorio_1h_enviado { get; set; }
        public Nullable<bool> confirmacion_asistencia_manitas { get; set; }
        public string inasistencia_reportada_por { get; set; }
        public Nullable<System.DateTime> fecha_inasistencia { get; set; }
    
        public virtual servicio servicio { get; set; }
    }
}
