//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manitas.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class direcciones_cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public direcciones_cliente()
        {
            this.servicios = new HashSet<servicio>();
        }
    
        public System.Guid id { get; set; }
        public System.Guid usuario_id { get; set; }
        public System.Guid colonia_id { get; set; }
        public string calle { get; set; }
        public string numero_ext { get; set; }
        public string numero_int { get; set; }
        public string referencias { get; set; }
        public string etiqueta { get; set; }
        public bool activa { get; set; }
    
        public virtual colonia colonia { get; set; }
        public virtual usuario usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<servicio> servicios { get; set; }
    }
}
