//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manitas.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class disputa
    {
        public System.Guid id { get; set; }
        public System.Guid servicio_id { get; set; }
        public System.Guid cliente_id { get; set; }
        public System.Guid manitas_id { get; set; }
        public Nullable<System.Guid> agente_id { get; set; }
        public string motivo_cliente { get; set; }
        public string estado { get; set; }
        public string resolucion { get; set; }
        public string justificacion_agente { get; set; }
        public string nota_advertencia_manitas { get; set; }
        public System.DateTime fecha_apertura { get; set; }
        public Nullable<System.DateTime> fecha_resolucion { get; set; }
        public System.DateTime sla_limite { get; set; }
    
        public virtual usuario usuario { get; set; }
        public virtual usuario usuario1 { get; set; }
        public virtual usuario usuario2 { get; set; }
        public virtual servicio servicio { get; set; }
    }
}
