//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manitas.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fotos_sesion
    {
        public System.Guid id { get; set; }
        public System.Guid sesion_id { get; set; }
        public string tipo { get; set; }
        public string url { get; set; }
        public System.DateTime fecha_subida { get; set; }
    
        public virtual sesione sesione { get; set; }
    }
}
