//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manitas.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fotos_galeria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public fotos_galeria()
        {
            this.reportes_galeria = new HashSet<reportes_galeria>();
        }
    
        public System.Guid id { get; set; }
        public System.Guid manitas_id { get; set; }
        public string url { get; set; }
        public string estado { get; set; }
        public short total_reportes { get; set; }
        public System.DateTime fecha_subida { get; set; }
        public Nullable<System.DateTime> fecha_retiro { get; set; }
    
        public virtual usuario usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reportes_galeria> reportes_galeria { get; set; }
    }
}
