//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manitas.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class identidades_bloqueadas
    {
        public System.Guid id { get; set; }
        public string correo { get; set; }
        public string ine_hash { get; set; }
        public string motivo { get; set; }
        public System.DateTime fecha_bloqueo { get; set; }
    }
}
