//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manitas.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class manitas_zonas
    {
        public System.Guid id { get; set; }
        public System.Guid perfil_manitas_id { get; set; }
        public System.Guid zona_id { get; set; }
    
        public virtual perfiles_manitas perfiles_manitas { get; set; }
        public virtual zona zona { get; set; }
    }
}
