//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manitas.Data.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Manitas_DBPilotoEntities : DbContext
    {
        public Manitas_DBPilotoEntities()
            : base("name=Manitas_DBPilotoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<calificaciones_manitas> calificaciones_manitas { get; set; }
        public virtual DbSet<cargos_comision> cargos_comision { get; set; }
        public virtual DbSet<ciclos_comision> ciclos_comision { get; set; }
        public virtual DbSet<colonia> colonias { get; set; }
        public virtual DbSet<configuracion_sistema> configuracion_sistema { get; set; }
        public virtual DbSet<controle> controles { get; set; }
        public virtual DbSet<conversacione> conversaciones { get; set; }
        public virtual DbSet<cotizacione> cotizaciones { get; set; }
        public virtual DbSet<diagnostico> diagnosticos { get; set; }
        public virtual DbSet<direcciones_cliente> direcciones_cliente { get; set; }
        public virtual DbSet<disputa> disputas { get; set; }
        public virtual DbSet<fotos_contacto_inicial> fotos_contacto_inicial { get; set; }
        public virtual DbSet<fotos_galeria> fotos_galeria { get; set; }
        public virtual DbSet<fotos_sesion> fotos_sesion { get; set; }
        public virtual DbSet<identidades_bloqueadas> identidades_bloqueadas { get; set; }
        public virtual DbSet<manitas_servicios> manitas_servicios { get; set; }
        public virtual DbSet<manitas_zonas> manitas_zonas { get; set; }
        public virtual DbSet<mensaje> mensajes { get; set; }
        public virtual DbSet<notificacione> notificaciones { get; set; }
        public virtual DbSet<pagos_comision> pagos_comision { get; set; }
        public virtual DbSet<partidas_cotizacion> partidas_cotizacion { get; set; }
        public virtual DbSet<perfiles_clientes> perfiles_clientes { get; set; }
        public virtual DbSet<perfiles_manitas> perfiles_manitas { get; set; }
        public virtual DbSet<reportes_galeria> reportes_galeria { get; set; }
        public virtual DbSet<rol_controles> rol_controles { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<servicio> servicios { get; set; }
        public virtual DbSet<sesione> sesiones { get; set; }
        public virtual DbSet<suspensione> suspensiones { get; set; }
        public virtual DbSet<tipos_servicio> tipos_servicio { get; set; }
        public virtual DbSet<usuario_roles> usuario_roles { get; set; }
        public virtual DbSet<usuario> usuarios { get; set; }
        public virtual DbSet<zona> zonas { get; set; }
    }
}
