//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manitas.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mensaje
    {
        public System.Guid id { get; set; }
        public System.Guid conversacion_id { get; set; }
        public System.Guid remitente_id { get; set; }
        public string tipo { get; set; }
        public string contenido { get; set; }
        public string archivo_url { get; set; }
        public System.DateTime fecha_envio { get; set; }
        public bool leido { get; set; }
    
        public virtual conversacione conversacione { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
