//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manitas.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class notificacione
    {
        public System.Guid id { get; set; }
        public System.Guid usuario_id { get; set; }
        public string tipo_evento { get; set; }
        public string urgencia { get; set; }
        public string canal { get; set; }
        public string destinatario_correo { get; set; }
        public string asunto { get; set; }
        public string cuerpo { get; set; }
        public string estado { get; set; }
        public short intentos { get; set; }
        public System.DateTime fecha_programada { get; set; }
        public Nullable<System.DateTime> fecha_envio { get; set; }
        public Nullable<System.Guid> reenviada_por_admin_id { get; set; }
        public Nullable<System.DateTime> fecha_reenvio { get; set; }
    
        public virtual usuario usuario { get; set; }
        public virtual usuario usuario1 { get; set; }
    }
}
