//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manitas.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pagos_comision
    {
        public System.Guid id { get; set; }
        public System.Guid ciclo_id { get; set; }
        public System.Guid manitas_id { get; set; }
        public decimal monto { get; set; }
        public string clabe_origen { get; set; }
        public string metodo { get; set; }
        public bool detectado_automaticamente { get; set; }
        public Nullable<System.Guid> registrado_por_admin_id { get; set; }
        public System.DateTime fecha_pago { get; set; }
        public System.DateTime fecha_registro { get; set; }
    
        public virtual ciclos_comision ciclos_comision { get; set; }
        public virtual usuario usuario { get; set; }
        public virtual usuario usuario1 { get; set; }
    }
}
