//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manitas.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class perfiles_clientes
    {
        public System.Guid id { get; set; }
        public System.Guid usuario_id { get; set; }
        public short inasistencias_consecutivas { get; set; }
        public short suspensiones_en_6_meses { get; set; }
        public string estado { get; set; }
        public Nullable<System.DateTime> fecha_reactivacion { get; set; }
    
        public virtual usuario usuario { get; set; }
    }
}
