//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manitas.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class perfiles_manitas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public perfiles_manitas()
        {
            this.manitas_servicios = new HashSet<manitas_servicios>();
            this.manitas_zonas = new HashSet<manitas_zonas>();
        }
    
        public System.Guid id { get; set; }
        public System.Guid usuario_id { get; set; }
        public string apodo { get; set; }
        public string descripcion { get; set; }
        public Nullable<short> anios_experiencia { get; set; }
        public string disponibilidad_texto { get; set; }
        public string foto_perfil_url { get; set; }
        public string ine_frente_url { get; set; }
        public string ine_reverso_url { get; set; }
        public string comprobante_url { get; set; }
        public string estado { get; set; }
        public string motivo_rechazo { get; set; }
        public int servicios_completados_total { get; set; }
        public short calificaciones_neg_consecutivas { get; set; }
        public bool terminos_calidad_aceptados { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<manitas_servicios> manitas_servicios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<manitas_zonas> manitas_zonas { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
