//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manitas.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reportes_galeria
    {
        public System.Guid id { get; set; }
        public System.Guid foto_id { get; set; }
        public System.Guid reportado_por_id { get; set; }
        public string motivo { get; set; }
        public System.DateTime fecha_reporte { get; set; }
        public bool ignorado { get; set; }
    
        public virtual fotos_galeria fotos_galeria { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
