//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manitas.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class servicio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public servicio()
        {
            this.calificaciones_manitas = new HashSet<calificaciones_manitas>();
            this.cargos_comision = new HashSet<cargos_comision>();
            this.conversaciones = new HashSet<conversacione>();
            this.cotizaciones = new HashSet<cotizacione>();
            this.diagnosticos = new HashSet<diagnostico>();
            this.disputas = new HashSet<disputa>();
            this.sesiones = new HashSet<sesione>();
        }
    
        public System.Guid id { get; set; }
        public System.Guid cliente_id { get; set; }
        public System.Guid manitas_id { get; set; }
        public Nullable<System.Guid> tipo_servicio_id { get; set; }
        public Nullable<System.Guid> zona_id { get; set; }
        public Nullable<System.Guid> direccion_id { get; set; }
        public Nullable<System.Guid> conversacion_id { get; set; }
        public string estado { get; set; }
        public string motivo_cierre { get; set; }
        public System.DateTime fecha_inicio { get; set; }
        public Nullable<System.DateTime> fecha_cierre { get; set; }
        public Nullable<System.DateTime> autocierre_programado { get; set; }
        public string cancelado_por { get; set; }
        public string motivo_cancelacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<calificaciones_manitas> calificaciones_manitas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cargos_comision> cargos_comision { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<conversacione> conversaciones { get; set; }
        public virtual conversacione conversacione { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cotizacione> cotizaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<diagnostico> diagnosticos { get; set; }
        public virtual direcciones_cliente direcciones_cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<disputa> disputas { get; set; }
        public virtual usuario usuario { get; set; }
        public virtual usuario usuario1 { get; set; }
        public virtual tipos_servicio tipos_servicio { get; set; }
        public virtual zona zona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sesione> sesiones { get; set; }
    }
}
