//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manitas.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sesione
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sesione()
        {
            this.fotos_sesion = new HashSet<fotos_sesion>();
        }
    
        public System.Guid id { get; set; }
        public System.Guid servicio_id { get; set; }
        public short numero_sesion { get; set; }
        public System.DateTime fecha_programada { get; set; }
        public System.TimeSpan hora_programada { get; set; }
        public string estado { get; set; }
        public Nullable<bool> ocurrio { get; set; }
        public string bitacora_texto { get; set; }
        public Nullable<System.DateTime> fecha_completada { get; set; }
        public string inasistencia_reportada_por { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fotos_sesion> fotos_sesion { get; set; }
        public virtual servicio servicio { get; set; }
    }
}
