//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manitas.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class suspensione
    {
        public System.Guid id { get; set; }
        public System.Guid usuario_id { get; set; }
        public string rol_afectado { get; set; }
        public string tipo { get; set; }
        public string motivo { get; set; }
        public System.DateTime fecha_inicio { get; set; }
        public Nullable<System.DateTime> fecha_fin { get; set; }
        public bool reactivacion_automatica { get; set; }
        public bool reactivado { get; set; }
        public Nullable<System.Guid> aplicada_por_admin_id { get; set; }
    
        public virtual usuario usuario { get; set; }
        public virtual usuario usuario1 { get; set; }
    }
}
