//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manitas.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario_roles
    {
        public System.Guid id { get; set; }
        public System.Guid usuario_id { get; set; }
        public System.Guid rol_id { get; set; }
        public bool activo { get; set; }
        public System.DateTime fecha_asignacion { get; set; }
    
        public virtual role role { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
